### ISSUE TITLE
Trigger event when video ends

### ISSUE THREAD

**Issue by philecom** [poxrud/youtube-directive-example#2]
First of all I will like to thank you for taking your time to develop this wonderful directive for angular. I have tried and it did work both on mobile and desktop.
there is these three things I will be glad if you can help me solve.
1) trigger an event when the video ends,
2) remove the suggested video after the end of the video.
3) Add full screen/restore button
4) Add mute button.
5) I get this warning in my console.
"Uncaught SecurityError: Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "http://localhost".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match."
 Although the vide works alright, I dont know if it will have an unexpected effect on the app.

Thank you.

**Comment by poxrud** [comment]
@philecom 
1. This is already in the code https://github.com/poxrud/youtube-directive-example/blob/master/application.js#L81-L83
2.  Take a look at http://stackoverflow.com/questions/11900442/youtube-player-api-hide-controls-hide-info-hide-related-videos. Looks like you need to set "rel: 0" in the playerVars object.
3. You need to use the HTML5 requestFullScreen() API. See https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
4. It's in youtube iframe documentation. Use player.mute(), player.unMute();
https://developers.google.com/youtube/iframe_api_reference
5. You're testing your player on your local computer with the "http" protocol but connecting to youtube's "https" protocol. Try connecting to youtube's iframe using "http".

**Comment by philecom** [comment]
Thank you man... More kisses on your cheeks.
